interface Version {
  id: Int
  name: String
}

type Employer  implements Version {
  id: Int
  name: String
  employees: [Employee]
}

type Employee implements Version{
  id: Int
  name: String
  employer: Employer
}
type Query {
  employees: [Version]
}
type Mutation {
  addEmployee(name: String!, employerId: Int!): Version
}